import hashlib
import json
from pathlib import Path
from types import SimpleNamespace
import sys
import tempfile
import unittest
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / 'scripts'))
from observability_api import Observability

class NativeActivationObservabilityTest(unittest.TestCase):
    def fixture(self, directory):
        folder=Path(directory)/('a'*32);folder.mkdir()
        request=b'{"messages":[{"role":"user","content":"actual request"}]}'
        (folder/'request.bin').write_bytes(request)
        (folder/'response.bin').write_text(json.dumps({'choices':[{'message':{'content':'original answer'},'finish_reason':'stop'}]}))
        (folder/'exchange.json').write_text(json.dumps({'request_id':folder.name,'session':'native-session','kind':'completion','started_at':1,'complete':True,'status':200}))
        rendered='actual rendered request'
        (folder/'activation-replay-preflight.json').write_text(json.dumps({'rendered_prompt':rendered}))
        source={'native_request_id':folder.name,'request_id':folder.name,'session':'native-session','request_sha256':hashlib.sha256(request).hexdigest(),'rendered_prompt_sha256':hashlib.sha256(rendered.encode()).hexdigest()}
        replay={'kind':'new_instrumented_real_request_replay','passed':True,'source':source,'rendered_prompt':rendered,'generated_text':'replay answer','samples':[], 'replay':{'run_id':'replay-run','trace_id':'replay-trace','experiment_id':'3','elapsed_ms':123,'started_at':2}}
        api=Observability(SimpleNamespace(directory=Path(directory)),{})
        return folder,source,replay,api

    def test_auxiliary_title_generation_does_not_replace_answer(self):
        with tempfile.TemporaryDirectory() as directory:
            folder,source,replay,api=self.fixture(directory)
            title=Path(directory)/('c'*32);title.mkdir()
            (title/'exchange.json').write_text(json.dumps({'request_id':title.name,'session':'native-session','kind':'completion','started_at':2,'complete':True,'status':200}))
            (title/'request.bin').write_text(json.dumps({'messages':[{'role':'user','content':'Based on the following interaction, generate a short, concise title (maximum 6-8 words): actual context'}]}))
            (title/'response.bin').write_text(json.dumps({'choices':[{'message':{'content':'Autogenerated title'},'finish_reason':'stop'}]}))
            detail=api.detail('native-session')
            self.assertEqual(detail['session']['latest_output'],'original answer')
            node=detail['nodes'][-1]
            self.assertEqual(node['category'],'title_generation')
            self.assertTrue(node['auxiliary'])
            self.assertEqual(node['name'],'Chat title generation')
            self.assertTrue(node['generation_available'])

    def test_pending_status_is_bound_and_does_not_invent_activations(self):
        with tempfile.TemporaryDirectory() as directory:
            folder,source,replay,api=self.fixture(directory)
            (folder/'activation-replay-status.json').write_text(json.dumps({'status':'queued','source':source}))
            node=api.detail('native-session')['nodes'][0]
            self.assertEqual(node['activation_replay_status']['status'],'queued')
            self.assertNotIn('activation_replay',node)
            self.assertEqual(node['activations']['status'],'not_captured')
            source['request_sha256']='foreign'
            (folder/'activation-replay-status.json').write_text(json.dumps({'status':'running','source':source}))
            self.assertEqual(api.detail('native-session')['nodes'][0]['activation_replay_status']['status'],'error')

    def test_exact_native_replay_separate_trace_and_original_preserved(self):
        with tempfile.TemporaryDirectory() as directory:
            folder,source,replay,api=self.fixture(directory)
            (folder/'activation-replay.json').write_text(json.dumps(replay))
            data=api.detail('native-session'); original,child=data['nodes']
            self.assertEqual(original['response']['choices'][0]['message']['content'],'original answer')
            self.assertEqual(original['activations']['status'],'not_captured')
            self.assertEqual(original['activation_replay_status']['status'],'completed')
            self.assertEqual(child['trace_id'],'replay-trace')
            self.assertEqual(child['original_request_id'],original['id'])
            self.assertEqual(child['activations']['status'],'captured')
            self.assertEqual(child['timings'],[])
            self.assertEqual(data['edges'][-1]['type'],'replay_of')

    def test_native_request_session_and_rendered_context_mismatches_rejected(self):
        for key,value in [('native_request_id','b'*32),('session','another-session'),('request_sha256','wrong'),('rendered_prompt_sha256','wrong')]:
            with self.subTest(key=key),tempfile.TemporaryDirectory() as directory:
                folder,source,replay,api=self.fixture(directory)
                source[key]=value
                (folder/'activation-replay.json').write_text(json.dumps(replay))
                nodes=api.detail('native-session')['nodes']
                self.assertEqual(len(nodes),1)
                self.assertNotIn('activation_replay',nodes[0])
                self.assertEqual(nodes[0]['activation_replay_status']['status'],'error')
        with tempfile.TemporaryDirectory() as directory:
            folder,source,replay,api=self.fixture(directory)
            replay['rendered_prompt']='different context'
            (folder/'activation-replay.json').write_text(json.dumps(replay))
            self.assertNotIn('activation_replay',api.detail('native-session')['nodes'][0])

    def test_per_turn_comparison_replays_do_not_require_global_singleton(self):
        with tempfile.TemporaryDirectory() as directory:
            folder=Path(directory)/('b'*32); model=folder/'qwen';model.mkdir(parents=True)
            nodes=[]
            for turn in (1,2):
                p=model/f'turn-{turn}';p.mkdir();raw=json.dumps({'turn':turn}).encode();rendered=f'actual qwen {turn}'
                (p/'request.json').write_bytes(raw);(p/'preflight.json').write_text(json.dumps({'rendered_prompt':rendered}))
                source={'comparison_run_id':folder.name,'model':'qwen','turn':turn,'request_sha256':hashlib.sha256(raw).hexdigest(),'rendered_prompt_sha256':hashlib.sha256(rendered.encode()).hexdigest()}
                (p/'activation-replay-status.json').write_text(json.dumps({'status':'running','source':source}))
                replay={'kind':'new_instrumented_real_request_replay','passed':True,'source':source,'rendered_prompt':rendered,'replay':{'run_id':str(turn)}}
                (p/'activation-replay.json').write_text(json.dumps(replay));nodes.append({'id':f'node{turn}','kind':'completion','turn':turn})
            api=Observability(SimpleNamespace(directory=Path(directory)),{})
            edges=[];api.attach_comparison_replay(folder,'qwen',nodes,edges)
            self.assertEqual(len(nodes),4)
            self.assertEqual(len(edges),2)
            self.assertTrue(all(n['activation_replay_status']['status']=='completed' for n in nodes[:2]))
            self.assertEqual(nodes[0]['activation_replay']['source']['model'],'qwen')

if __name__=='__main__': unittest.main()
